# ============================================
# PDF_SERVICE.PY - Servicio de Generación de PDFs
# ============================================
# Este archivo convierte el texto legal generado por la IA en un PDF descargable

# Importa FPDF, una librería de Python para crear PDFs
from fpdf import FPDF

# Importa os para manejar rutas de archivos y crear directorios
import os

# ============================================
# CLASE PERSONALIZADA DE PDF
# ============================================
class LegalPDF(FPDF):
    """
    Clase que extiende FPDF para agregar header y footer personalizados.
    Hereda de FPDF y sobrescribe los métodos header() y footer().
    """
    
    def header(self):
        """
        Este método se llama AUTOMÁTICAMENTE al inicio de cada página.
        Agrega el encabezado con el nombre de JustiBot.
        """
        # Configura fuente: Arial, negrita (B), tamaño 12
        self.set_font('Arial', 'B', 12)
        
        # Crea una celda con el título
        # Parámetros: (ancho, alto, texto, borde, salto_línea, alineación)
        # 0 = ancho completo de la página
        # 1 = saltar a la siguiente línea después
        # 'C' = centrado
        self.cell(0, 10, 'Generated by JustiBot - Legal Assistant', 0, 1, 'C')
        
        # Agrega espacio vertical de 10mm después del header
        self.ln(10)

    def footer(self):
        """
        Este método se llama AUTOMÁTICAMENTE al final de cada página.
        Agrega el número de página en el footer.
        """
        # Posiciona el cursor a 15mm desde el fondo de la página
        self.set_y(-15)
        
        # Configura fuente: Arial, itálica (I), tamaño 8
        self.set_font('Arial', 'I', 8)
        
        # Imprime el número de página
        # self.page_no() retorna el número de la página actual
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

# ====================================================================================
# FUNCIÓN PRINCIPAL: CREAR PDF
# ====================================================================================
def create_pdf(case_id: int, content: str, user_name: str, user_id: str, city: str):
    """
    Genera un documento PDF profesional con el texto legal y los datos del ciudadano.
    
    Parámetros:
        case_id (int): ID único del caso en la base de datos (ej: 1, 2, 3...)
        content (str): Texto legal generado por la IA
        user_name (str): Nombre completo del ciudadano
        user_id (str): Número de cédula de ciudadanía
        city (str): Ciudad de residencia
    
    Retorna:
        str: Nombre del archivo PDF (ej: "case_1.pdf")
        
    Ejemplo de uso:
        pdf_name = create_pdf(1, "De conformidad...", "Juan Pérez", "123456", "Bogotá")
        # Retorna: "case_1.pdf"
        # El archivo se guarda en: /app/static/case_1.pdf
    """
    
    # ============================================
    # PASO 1: Crear instancia de PDF personalizado
    # ============================================
    # Usa nuestra clase LegalPDF que tiene header y footer automáticos
    pdf = LegalPDF()
    
    # Agrega una nueva página en blanco
    # Esto llama automáticamente a header()
    pdf.add_page()
    
    # Configura la fuente para el contenido principal
    # Arial, normal (sin B ni I), tamaño 12
    pdf.set_font("Arial", size=12)
    
    # ============================================
    # PASO 2: Agregar metadatos del usuario
    # ============================================
    # cell(ancho, alto, texto, salto_línea)
    # ln=True hace que salte a la siguiente línea después de imprimir
    pdf.cell(0, 10, f"Ciudad: {city}", ln=True)
    pdf.cell(0, 10, f"Solicitante: {user_name} - CC: {user_id}", ln=True)
    
    # Agrega espacio vertical de 10mm
    pdf.ln(10)
    
    # ============================================
    # PASO 3: Agregar contenido legal
    # ============================================
    # multi_cell es como cell pero permite texto largo que se divide en múltiples líneas
    # 
    # ¿Por qué .encode('latin-1', 'replace').decode('latin-1')?
    # - FPDF tiene problemas con caracteres UTF-8 (á, ñ, é, etc.)
    # - Convertimos a latin-1 que SÍ soporta español
    # - 'replace' reemplaza caracteres incompatibles en lugar de fallar
    pdf.multi_cell(0, 10, content.encode('latin-1', 'replace').decode('latin-1'))
    
    # ============================================
    # PASO 4: Guardar el PDF en disco
    # ============================================
    # Construye el nombre del archivo
    filename = f"case_{case_id}.pdf"
    
    # Construye la ruta completa DENTRO del contenedor Docker
    # /app/static/ es el directorio montado en docker-compose.yml
    path = f"/app/static/{filename}"
    
    # Crea el directorio /app/static si no existe
    # exist_ok=True evita error si el directorio ya existe
    os.makedirs("/app/static", exist_ok=True)
    
    # Guarda el PDF en el archivo
    # Esto escribe el PDF en disco en la ruta especificada
    pdf.output(path)
    
    # Retorna solo el nombre del archivo (sin la ruta completa)
    # Este nombre se guardará en la base de datos en el campo pdf_path
    return filename
